/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Sum, SumInterface } from "../Sum";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "quoteExactInput",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Sum__factory {
  static readonly abi = _abi;
  static createInterface(): SumInterface {
    return new utils.Interface(_abi) as SumInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Sum {
    return new Contract(address, _abi, signerOrProvider) as Sum;
  }
}
